#############################################################################
# Makefile for building: qdyn2ex_test.app/Contents/MacOS/qdyn2ex_test
# Generated by qmake (3.1) (Qt 5.15.10)
# Project:  qdyn2exodus_constanza.pro
# Template: app
# Command: /opt/homebrew/bin/qmake -o Makefile qdyn2exodus_constanza.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.5 -w -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.5 -w -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../libmesh/libmesh/installed/include -I../../libmesh/libmesh/installed/include/libmesh -I/opt/homebrew/Cellar/open-mpi/5.0.0/include -I/opt/homebrew/Cellar/open-mpi/5.0.0/include/openmpi -I/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt@5/5.15.10_1/lib
QMAKE         = /opt/homebrew/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qdyn2ex_test1.0.0
DISTDIR = /Users/crpiceda/qdyn2exodus/qdyn2exodus/.tmp/qdyn2ex_test1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -Wl,-rpath,/Users/crpiceda/libmesh/libmesh/installed/lib -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.5 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/opt/homebrew/Cellar/qt@5/5.15.10_1/lib -L/Users/crpiceda/libmesh/libmesh/installed/lib -L/opt/homebrew/Cellar/open-mpi/5.0.0/lib -lmpi -lmesh_opt -ldl -lpthread -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webengine.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/default_pre.prf \
		qdyn2exodus_constanza.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/warn_off.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/lex.prf \
		qdyn2exodus_constanza.pro helper.h \
		geometry.h main.cpp
QMAKE_TARGET  = qdyn2ex_test
DESTDIR       = 
TARGET        = qdyn2ex_test.app/Contents/MacOS/qdyn2ex_test

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 14.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/crpiceda/qdyn2exodus/qdyn2exodus/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/crpiceda/qdyn2exodus/qdyn2exodus/qdyn2exodus_constanza.pro


include /opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

qdyn2ex_test.app/Contents/MacOS/qdyn2ex_test:  $(OBJECTS)  
	@test -d qdyn2ex_test.app/Contents/MacOS/ || mkdir -p qdyn2ex_test.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qdyn2exodus_constanza.pro /opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/macx-clang/qmake.conf /opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webengine.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/default_pre.prf \
		qdyn2exodus_constanza.pri \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/warn_off.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/lex.prf \
		qdyn2exodus_constanza.pro \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile qdyn2exodus_constanza.pro
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/spec_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/qdevice.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/common/clang-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/qconfig.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gamepad.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_macextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdf.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdf_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdfwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_purchasing.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_script.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_script_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scripttools.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webengine.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/sdk.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/default_pre.prf:
qdyn2exodus_constanza.pri:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resolve_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/warn_off.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/mac.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qt.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resources_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/resources.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/moc.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/unix/opengl.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/uic.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/unix/thread.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/qmake_use.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/file_copies.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/rez.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/testcase_targets.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/exceptions.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/yacc.prf:
/opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/lex.prf:
qdyn2exodus_constanza.pro:
/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtGui.framework/Resources/QtGui.prl:
/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qdyn2exodus_constanza.pro

qmake_all: FORCE

qdyn2ex_test.app/Contents/PkgInfo: 
	@test -d qdyn2ex_test.app/Contents || mkdir -p qdyn2ex_test.app/Contents
	@$(DEL_FILE) qdyn2ex_test.app/Contents/PkgInfo
	@echo "APPL????" > qdyn2ex_test.app/Contents/PkgInfo
qdyn2ex_test.app/Contents/Resources/empty.lproj: 
	@test -d qdyn2ex_test.app/Contents/Resources || mkdir -p qdyn2ex_test.app/Contents/Resources
	@touch qdyn2ex_test.app/Contents/Resources/empty.lproj
	
qdyn2ex_test.app/Contents/Info.plist: 
	@test -d qdyn2ex_test.app/Contents || mkdir -p qdyn2ex_test.app/Contents
	@$(DEL_FILE) qdyn2ex_test.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.qdyn2ex-test,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.qdyn2ex-test,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},13.5,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,qdyn2ex_test,g" -e "s,@LIBRARY@,qdyn2ex_test,g" -e "s,\$${EXECUTABLE_NAME},qdyn2ex_test,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/macx-clang/Info.plist.app >qdyn2ex_test.app/Contents/Info.plist

all: Makefile \
		qdyn2ex_test.app/Contents/PkgInfo \
		qdyn2ex_test.app/Contents/Resources/empty.lproj \
		qdyn2ex_test.app/Contents/Info.plist qdyn2ex_test.app/Contents/MacOS/qdyn2ex_test

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents helper.h geometry.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r qdyn2ex_test.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.5 -w -dM -E -o moc_predefs.h /opt/homebrew/Cellar/qt@5/5.15.10_1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp /opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/QtCore \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qglobal.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qabstractanimation.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qabstracteventdispatcher.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qabstractnativeeventfilter.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qabstractproxymodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qabstractstate.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qabstracttransition.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qalgorithms.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qanimationgroup.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qarraydata.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qarraydataops.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qarraydatapointer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qatomic.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qbasictimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qbitarray.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qbuffer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qbytearraylist.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qbytearraymatcher.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcache.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcalendar.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcborarray.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcborcommon.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcbormap.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcborstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcborstreamreader.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcborstreamwriter.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcborvalue.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qchar.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcollator.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcommandlineoption.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcommandlineparser.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcompilerdetection.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qconcatenatetablesproxymodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcontainerfwd.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcontiguouscache.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcoreapplication.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcoreevent.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qcryptographichash.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qdatastream.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qdeadlinetimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qdir.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qdiriterator.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qeasingcurve.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qelapsedtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qendian.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qeventloop.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qeventtransition.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qexception.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfactoryinterface.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfiledevice.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfileinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfileselector.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfilesystemwatcher.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfinalstate.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qflags.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfuture.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfutureinterface.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfuturesynchronizer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qfuturewatcher.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qgenericatomic.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qglobalstatic.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qhash.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qhashfunctions.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qhistorystate.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qidentityproxymodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qiodevice.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qisenum.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qiterator.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qjsonarray.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qjsonvalue.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qlibrary.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qlibraryinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qline.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qlinkedlist.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qlist.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qlocale.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qlockfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qloggingcategory.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmargins.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmath.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmessageauthenticationcode.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmetaobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmetatype.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmimedata.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmimedatabase.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmimetype.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qmutex.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qnamespace.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qnumeric.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qobjectcleanuphandler.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qobjectdefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qoperatingsystemversion.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qpair.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qparallelanimationgroup.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qpauseanimation.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qplugin.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qpluginloader.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qpoint.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qpointer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qprocessordetection.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qpropertyanimation.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qqueue.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qrandom.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qreadwritelock.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qrect.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qrefcount.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qregexp.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qregularexpression.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qresource.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qresultstore.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qrunnable.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsavefile.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qscopedpointer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qscopedvaluerollback.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qscopeguard.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsemaphore.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsequentialanimationgroup.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qset.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qshareddata.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsharedmemory.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsharedpointer.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsignalmapper.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsignaltransition.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsize.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsocketnotifier.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsortfilterproxymodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstack.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstandardpaths.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstate.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstatemachine.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstorageinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstringalgorithms.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstringbuilder.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstringlist.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstringlistmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstringliteral.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstringmatcher.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qstringview.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsysinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsystemdetection.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qsystemsemaphore.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtemporarydir.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtextboundaryfinder.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtextcodec.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qthreadpool.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qthreadstorage.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtimeline.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtimezone.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtranslator.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtransposeproxymodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtypeinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtypetraits.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qurl.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qurlquery.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/quuid.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qvariantanimation.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qvarlengtharray.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qvector.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qversionnumber.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qversiontagging.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qwaitcondition.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qwineventnotifier.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qxmlstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/qtcoreversion.h \
		../../libmesh/libmesh/installed/include/libmesh/exodusII.h \
		../../libmesh/libmesh/installed/include/netcdf.h \
		/opt/homebrew/opt/libomp/include/omp.h \
		helper.h \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/QDebug \
		/opt/homebrew/Cellar/qt@5/5.15.10_1/lib/QtCore.framework/Headers/QTextStream \
		geometry.h \
		/usr/local/opt/libomp/include/omp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

